# Generated by Django 5.0 on 2024-10-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
