# Generated by Django 5.0 on 2024-10-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_otp_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
