# Generated by Django 5.0 on 2024-10-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_otp_mobile_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_verified',
        ),
    ]
